#! /usr/bin/env bash
# Info: 
# Download: 
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${SOURCE_DIR}"
BASE="$PWD"
cd "${SOURCE_DIR}"

source config.sh

IDENT_URL='https://archive.org/advancedsearch.php?q=subject%3Aterroroftinytown&fl%5B%5D=identifier&sort%5B%5D=titleSorter+asc&sort%5B%5D=&sort%5B%5D=&rows=5000&page=1&callback=callback&save=yes&output=csv'

IDENT_LIST="identifiers.csv"
IDENT_AGE=1024
if [ -f "./identifiers.csv" ]; then
  IDENT_AGE="$(echo "($(date --utc +%s) - $(date +%s -r "$IDENT_LIST"))/86400" | bc)"
fi

if [ $IDENT_AGE -gt 7 ]; then
    echo "[INFO] $IDENT_LIST is more than 7 days old. Re-downloading." 1>&2
else
    echo "[INFO] $IDENT_LIST is less than 7 days old, using it." 1>&2
fi

if [ ! -e "$IDENT_LIST" ] || [ "x$1" = "x--update-identifiers" ] || [ $IDENT_AGE -gt 7 ]; then
  curl -s "$IDENT_URL" | grep -v identifier | tr -d '"' > "$IDENT_LIST"
fi

BASE_TORRENT_URL="https://archive.org/download/%s/%s_archive.torrent"

mkdir -p "$TORRENT_PATH"

wget --continue --directory-prefix="$TORRENT_PATH" 'https://archive.org/download/URLTeamTorrentRelease2013July/URLTeamTorrentRelease2013July_archive.torrent';

cat "$IDENT_LIST" | while read IDENT;
do
  TORRENT_URL=$(printf "$BASE_TORRENT_URL\n" "$IDENT" "$IDENT");
  TORRENT_FILE="$TORRENT_PATH/${IDENT}_archive.torrent";
  if [ -e "$TORRENT_FILE" ] && [ "x$1" != "x--update-torrents" ]; then
      echo "[INFO] Not downloading $TORRENT_FILE, use --update-torrents to override" 1>&2;
  elif [ -e "$TORRENT_PATH/${IDENT}_archive.torrent" ] && [ "x$1" = "x--update-torrents" ]; then
      echo "[INFO] Force download/overwrite of $TORRENT_FILE" 1>&2;
      wget -O "$TORRENT_FILE" "$TORRENT_URL" || exit 1;
  else
    echo "[INFO] Downloading $TORRENT_URL" 1>&2;
    wget --continue --directory-prefix="$TORRENT_PATH" "$TORRENT_URL" || exit 1;
  fi;
done;

