#! /bin/bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SOURCE_DIR" || exit
source config.sh

ME="$(basename "${BASH_SOURCE[0]}")"

set -euo pipefail

mkdir -p "$TORRENT_PATH"
mkdir -p "$STORAGE_PATH"
mkdir -p "$CACHE_PATH"

LOG_VERB=1
LOG_INFO=1
LOG_ERROR=1

BREAK="no"

IDENT_URL='https://archive.org/advancedsearch.php?q=subject%3Aterroroftinytown&fl%5B%5D=identifier&sort%5B%5D=titleSorter+asc&sort%5B%5D=&sort%5B%5D=&rows=5000&page=1&callback=callback&save=yes&output=csv'

IDENT_LIST="identifiers.csv"
IDENT_AGE=1024
if [ -f "./$IDENT_LIST" ]; then
  IDENT_AGE="$(echo "($(date --utc +%s) - $(date +%s -r "$IDENT_LIST"))/86400" | bc)"
fi

if [ $IDENT_AGE -gt 7 ]; then
    echo "[INFO] $IDENT_LIST is more than 7 days old. Re-downloading." 1>&2
else
    echo "[INFO] $IDENT_LIST is less than 7 days old, using it. (use --update-identifiers to force update)" 1>&2
fi

if [ ! -e "$IDENT_LIST" ] || [ "x--update-identifiers" = "${1:-}" ] || [ $IDENT_AGE -gt 7 ]; then
  curl -s "$IDENT_URL" | grep -v identifier | tr -d '"' > "$IDENT_LIST"
  exit
fi


if [ "--2013" = "${1:-}" ]; then
  IDENTS="URLTeamTorrentRelease2013July"
else
  IDENTS="$(sort -R identifiers.csv)"
fi

if [ ! -f "$PWD/ia" ]; then
  ERROR "Internet Archive downloader (ia) was not found in \$PWD. Download? (Enter or Ctrl-C)"
  read -r FOO
  wget https://archive.org/download/ia-pex/ia
  chmod +x "$PWD/ia"
fi

echo "$IDENTS" | while read -r IDENTIFIER;
  do
    OUTPUT="$IDENTIFIER.no.xz"
    OUTPUT_PATH="$STORAGE_PATH/simple_extract/$OUTPUT"
    if [ ! -f "$OUTPUT_PATH" ]; then
      INFO "Processing $IDENTIFIER, starting download... [$ME]"
      INFO "Starting at $(date +%F-%T)"
      if [ "$IDENTIFIER" != "URLTeamTorrentRelease2013July" ]; then
        TMP_FOLDER="$(mktemp -d "$STORAGE_PATH/$IDENTIFIER-XXXXXXXXXXX")"
      else
        TMP_FOLDER="$STORAGE_PATH/$IDENTIFIER"
      fi
      RC=0
      if [ "$IDENTIFIER" != "URLTeamTorrentRelease2013July" ]; then
        ./ia download --destdir="$TMP_FOLDER" --verbose "$IDENTIFIER" | sed -e 's/^/[INFO] /' -e "s/$/ [$ME]/" || RC=${?:-}
        if [ $RC -ne 0 ]; then
          echo >&2 "[ERROR] Failed to download $IDENTIFIER, exit code $RC"
          exit "$RC"
        fi
      fi
      INFO "Extracting '.no' from *.zip-files to $CACHE_PATH [$ME]"
      find "$TMP_FOLDER/" -type f -name '*.zip' | \
        parallel --jobs 7 "$SOURCE_DIR/cache_zip.sh" "$CACHE_PATH" "{}";

      INFO "Extracting '.no' from *.xz-files to $CACHE_PATH [$ME]"
      find "$TMP_FOLDER/" -type f -name '*.xz' | \
        parallel --jobs 7 "$SOURCE_DIR/cache_xz.sh" "$CACHE_PATH" "{}";

      INFO "Creating uniqe cache for $IDENTIFIER into $OUTPUT_PATH [$ME]"
      find "$CACHE_PATH" -name '*.xz' -exec xzcat {} \; | sort | uniq | \
        xz --compress -T 0 --stdout > "$OUTPUT_PATH.tmp"
      rm "$CACHE_PATH/"*
      mv "$OUTPUT_PATH.tmp" "$OUTPUT_PATH"
      if [ "$IDENTIFIER" != "URLTeamTorrentRelease2013July" ]; then
        # URLTeamTorrentRelease2013July is so large we don't want to delete it
        rm -r "$TMP_FOLDER"
      fi
      INFO "Finished $OUTPUT [$ME]"
    else
      VERB "Found $OUTPUT, not processing $IDENTIFIER again [$ME]"
    fi
done;
